# Generated by Django 3.0.4 on 2020-03-26 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('imageLink', models.CharField(max_length=200)),
                ('quantity', models.IntegerField(default=1, editable=False)),
            ],
        ),
    ]
