# Generated by Django 3.0.4 on 2020-03-26 23:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_details', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Product',
            new_name='ProductDetails',
        ),
        migrations.RenameField(
            model_name='productdetails',
            old_name='imageLink',
            new_name='image_link',
        ),
    ]
